spring.application.name=landhub

spring.datasource.url=jdbc:mysql://localhost:3306/landhub_db
<<<<<<< HEAD
spring.datasource.username=root
spring.datasource.password=Ashan20031213
=======
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
>>>>>>> 2f60836 (made the projecct structure)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

<<<<<<< HEAD
server.port=8080
=======
server.port=8080
>>>>>>> 2f60836 (made the projecct structure)
